[package]
name = "masq"
version = "1.0.0"
license = "GPL-3.0-only"
authors = ["MASQ"]
copyright = "Copyright (c) 2019, MASQ (https://masq.ai). All rights reserved."
description = "Command-line user interface for MASQ Node"
edition = "2018"

[dependencies]

[dev-dependencies]

[[bin]]
name = "masq"
path = "src/main.rs"

[lib]
name = "masq_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"
