[package]
name = "automap"
version = "1.0.0"
authors = ["Dan Wiebe <dnwiebe@gmail.com>", "MASQ"]
license = "GPL-3.0-only"
copyright = "Copyright (c) 2019-2021, MASQ (https://masq.ai) and/or its affiliates. All rights reserved."
description = "Library full of code to make routers map ports through firewalls"
edition = "2018"
workspace = "../node"

[dependencies]

[lib]
name = "automap"
path = "src/lib.rs"
