name: ci-matrix

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - release/*

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.os }}
        run: |
          rustup show
          rustup update stable
          ./ci/all.sh
        shell: bash
      - name: Publish ${{ matrix.os }}
        run: |
          ./ci/collect_results.sh
          ./ci/publish_results.sh
        shell: bash
        env:
          RESULTS_REPO_OWNER: masq-results
          RESULTS_REPO_NAME: MASQ-results
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
